kellyselden/ember-awesome-macros

README.md
addon/promise-object.js
tests/unit/promise-object-test.js

add promise-object

---

README.md
addon/to-lower.js
addon/to-upper.js
tests/unit/to-lower-test.js
tests/unit/to-upper-test.js

add toUpper and toLower

---

README.md
addon/equal-key.js
addon/gt-key.js
addon/gte-key.js
addon/index.js
addon/lt-key.js
addon/lte-key.js
tests/unit/equal-key-test.js
tests/unit/gt-key-test.js
tests/unit/gte-key-test.js
tests/unit/lt-key-test.js
tests/unit/lte-key-test.js

that have dependent properties on both sides

add Ember.computed equivalents

---

README.md
addon/index.js
addon/substr.js
addon/substring.js
tests/unit/substr-test.js
tests/unit/substring-test.js

add substr and substring

---

README.md
addon/index.js
addon/math.js
tests/integration/math-test.js
tests/unit/math-test.js

add math macro

---

README.md

Be proud of your Ember Observer score.

Added Ember Observer badge

---

README.md
addon/utils.js
package.json
tests/integration/computed-test.js

add computed key collapsing

---

README.md
addon/promise-array.js
addon/promise-object.js
addon/utils.js
tests/integration/promise-array-test.js
tests/integration/promise-object-test.js

remove function arg of promise macros

---

README.md
addon/index.js
addon/string/index.js
addon/string/length.js
tests/integration/string/length-test.js
tests/unit/string/length-test.js

add string.length

---

addon/and.js
addon/difference.js
addon/or.js
addon/product.js
addon/quotient.js
addon/sum.js
addon/utils.js
tests/integration/add-test.js
tests/integration/and-test.js
tests/integration/difference-test.js
tests/integration/divide-test.js
tests/integration/multiply-test.js
tests/integration/product-test.js
tests/integration/quotient-test.js
tests/integration/subtract-test.js
tests/integration/sum-test.js

stop removing undefined

---

README.md
addon/array/index.js
addon/array/reverse.js
tests/integration/array/reverse-test.js

add array.reverse macro

---

README.md
addon/index.js
addon/mod.js
tests/integration/mod-test.js

add modulus macro

---

README.md
addon/array/index.js
addon/array/sort.js
addon/utils.js
tests/integration/array/sort-test.js

add array sort macro

---

package.json

remove ember-data

---

README.md
addon/equal.js
tests/integration/equal-test.js

support N number of equal args

---

README.md
addon/index.js
addon/unless.js
tests/integration/unless-test.js

add unless macro

---

package.json

fix(package): update ember-macro-helpers to version 0.8.0

---

package.json

chore(package): update ember-macro-test-helpers to version 2.1.0

---

README.md
addon/array/index.js
addon/array/invoke.js
tests/integration/array/invoke-test.js
tests/unit/array/invoke-test.js

fixes #233 
please let me know if the coverage/implementation on this works for you

add array/invoke

---

package.json

remove ember-cli-test-loader

---

package.json

remove ember-cli-uglify

---

package.json

remove ember-cli-sri

---

addon/array/filter-by.js
addon/array/find-by.js
addon/array/invoke.js
addon/array/is-any.js
addon/array/is-every.js
addon/array/map-by.js
addon/array/uniq-by.js
tests/integration/array/invoke-test.js
tests/integration/filter-by-test.js
tests/integration/find-by-test.js
tests/integration/is-any-test.js
tests/integration/is-every-test.js
tests/integration/map-by-test.js
tests/integration/uniq-by-test.js

I would love to have @marcoow and @Turbo87 code reviews. Related PR https://github.com/kellyselden/ember-macro-helpers/pull/51.

add create-class-computed ability

---

tests/acceptance/array-imports-test.js
tests/acceptance/math-imports-test.js
tests/acceptance/promise-imports-test.js
tests/acceptance/string-imports-test.js
tests/acceptance/top-level-imports-test.js
tests/helpers/expect-imports.js

add tests for different import permutations

---

addon/math.js
index.js
package.json
tests/acceptance/math-imports-test.js
tests/integration/math-test.js

use broccoli file creator instead of babel plugin for math imports

---

README.md
addon/string/escape-expression.js
addon/string/index.js
tests/acceptance/string-imports-test.js
tests/integration/string/escape-expression-test.js

add escapeExpression macro

---

README.md
addon/string/index.js
addon/string/titleize.js
tests/acceptance/string-imports-test.js
tests/integration/string/titleize-test.js

add titleize macro

---

addon/-utils.js
addon/equal.js

fix and, or, and equal

---

README.md
addon/array/reduce.js
tests/integration/array/reduce-test.js

allow factory functions in reduce

---

README.md
addon/array/group-by.js
addon/array/index.js
tests/acceptance/array-imports-test.js
tests/integration/array/group-by-test.js

I've created the groupBy macro that behaves as you can see in the updated README.md
I found myself multiple times writing this kind of helper in my projects, so I thought it wold be a nice addition to this awesome addon.
I took inspiration from https://github.com/HeroicEric/ember-group-by that seems no longer maintained (I've sent a PR there months ago aswell).
Hope to have coded the macro correctly. It's working as intended but I don't know if the functionalities I took advance of from your libs are used in the right way.

Add groupBy macro

---

addon/array/-utils.js
addon/array/any.js
addon/array/every.js
addon/array/filter-by.js
addon/array/filter.js
addon/array/find-by.js
addon/array/includes.js
addon/array/index-of.js
addon/array/join.js
addon/array/last-index-of.js
addon/array/reject-by.js
addon/string/-utils.js
addon/string/split.js
tests/integration/array/filter-by-test.js
tests/integration/array/filter-test.js
tests/integration/array/reject-by-test.js
tests/integration/string/split-test.js

copy array default value

---

addon/array/filter-by.js
addon/array/is-any.js
addon/array/is-every.js
addon/array/reject-by.js
tests/integration/array/filter-by-test.js
tests/integration/array/is-any-test.js
tests/integration/array/is-every-test.js
tests/integration/array/reject-by-test.js

Closes #363.
cc @buschtoens
https://github.com/kellyselden/ember-awesome-macros/pull/363#issuecomment-315288517 Is still an issue.

allow optional args with filterBy and rejectBy

---

addon/array/-utils.js
tests/unit/array/utils/normalize-array-2-test.js
tests/unit/array/utils/normalize-array-3-test.js

@marcoow Does this look like the right direction?

ArrayProxy fix

---

package.json
tests/integration/array/compact-test.js
tests/integration/array/reverse-test.js
tests/integration/array/uniq-test.js
tests/integration/parse-float-test.js

Reverts kellyselden/ember-awesome-macros#404

Revert "Update eslint-config-sane to the latest version 🚀"

---

README.md
addon/index.js
addon/string/index.js
addon/string/trim.js
tests/acceptance/string-imports-test.js
tests/acceptance/top-level-imports-test.js
tests/integration/string/trim-test.js

add trim macro (#242)

---

addon/string/trim.js

cc @ctjhoa using the slightly newer helper for trim. It's insider knowledge, you just picked an older macro to copy. No big deal.

use normalizeString2 for trim

---

package.json

fix(package): update broccoli-file-creator to version 2.1.1

---

README.md
addon/index.js
addon/number.js
tests/acceptance/top-level-imports-test.js
tests/integration/number-test.js

Wraps https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number
Closes #455

Implement a Number composable macro

---

package-lock.json
package.json
tests/acceptance/array-imports-test.js
tests/acceptance/promise-imports-test.js
tests/acceptance/string-imports-test.js
tests/acceptance/top-level-imports-test.js
tests/helpers/expect-imports.js

use ember-macro-test-helpers/expect-imports

---

README.md
addon/bool.js
addon/index.js
tests/acceptance/top-level-imports-test.js
tests/integration/bool-test.js

add bool macro

---

addon/array/-utils.js
addon/array/first.js
addon/array/last.js
package-lock.json
package.json
tests/acceptance/many-array-test.js
tests/dummy/app/models/child.js
tests/dummy/app/models/parent.js
tests/unit/many-array-test.js

Resolves #423 
A failing test case is in a separate [commit](https://github.com/kellyselden/ember-awesome-macros/commit/1e55173a36847f783b14c9d942e49ad7c0e9da03) for your convenience.

Fix array macros for Ember.Array objects

---

package-lock.json
package.json

https://github.com/kellyselden/ember-macro-helpers/pull/222#issuecomment-463130842

revert babel 7

---

package-lock.json
package.json

Reverts kellyselden/ember-awesome-macros#539

Revert "revert babel 7"

---

package-lock.json
package.json

Version bump to include bug fix: https://github.com/kellyselden/ember-macro-helpers/pull/273
If cool with this (I was thinking it was a patch versus a minor, but not positive), would need a npm bump too. 
Thanks for making the fix!

Bump package to 5.0.1, bump ember-macro-helpers to 4.2.2

---

.eslintrc.js
package-lock.json
package.json

https://github.com/ember-cli/eslint-plugin-ember/issues/604

Update dependency eslint-plugin-ember to v7
